### ISSUE TITLE
アイディアソン 

### ISSUE THREAD

**Issue by Sorarinu** [Sorarinu/ProjectP_Team#1]
後期作るやつのアイディア

**Comment by Sorarinu** [comment]
田胡先生を倒す

**Comment by Koki07** [comment]
- 催眠による無意識通学
  - 催眠音声？

**Comment by namazu510** [comment]
電車で考えた
- 見たくない物を視界から消すアプリ　AR？
  　　たとえば、視界に映る人をぜんぶ木やかぼちゃやじゃがいもに変えよう、広告を全部真っ白にするとか
  　　個人的にはアイマスクして生活したいくらいだけどそれじゃさすがに不便すぎるからね
- うるさい会話を全部消すノイズキャンセラ←これBOSEのでよかったわむしろ耳栓でよかった
- 二次嫁にがんばれがんばれしてもらって褒めてもらって愚痴聞いてもらってお酒につきあってもらうサービスで元気だす

**Comment by Sorarinu** [comment]
VRでカメラを通して現実世界を拡張するのも面白そう．
VRゴーグルかけるとブラック企業の印が浮かび上がったり．

VRでやる意味あるのか？って感じもするけど

**Comment by Koki07** [comment]
現実世界を拡張だとARになるね。

スマホ越しに見てブラックかどうかの印が浮かび上がるって形になりそう。

**Comment by Sorarinu** [comment]
迷える就活生に向けたブラック判定ARw
やるとしたらマーカーレスARになるだろうから空間把握させないかんな

**Comment by namazu510** [comment]
VRでつくるメッセージングアプリの蔵（TwitterとかLineとかSkypeとかなんか）
相手のアバターが出てきて喋ってくれるんじゃ　
イメージは攻殻機動隊のこれじゃ
[がぞう](https://gyazo.com/7be6f4b9c581e269341639387260d09e)
どれだけ大変かはしらない

**Comment by namazu510** [comment]
作るものはブックマークの管理WEBAPPになりました
