### ISSUE TITLE
レイアウト崩れ

### ISSUE THREAD

**Issue by namazu510** [Sorarinu/ProjectP_Team#104]
INDEX,
https://gyazo.com/d9730160c4a12a273ebeea3ab9d152d8

**Comment by namazu510** [comment]
Choromeだとうまい感じに改行が入るみたいだね　Firefoxだとはいらないや

**Comment by namazu510** [comment]
上原さん　fix/issue104 みたいなブランチmasterから切ってそのうちなおしちゃってよ(´・ω・｀)
よろしく 🙏

**Comment by arinamako** [comment]
ほんとだ
りょうかいです！
