### ISSUE TITLE
レポート

### ISSUE THREAD

**Issue by namazu510** [Sorarinu/ProjectP_Team#117]
１つのレポートをグループで提出する

TODO: (書いたらチェックいれる）
- [x] システムの概要
- [x] プロトタイプの説明
- [x] 顧客インタビューとその解析
- [x] 結論
- [x] 質問内容とインタビュー結果
- [x] 次のプロトタイプ
- [x] 機能一覧
- [x] アーキテクチャ（システム構成図、仕様要件列挙）

TODO2:
- [x] レポート統合とか全体での統一
- [x] レポート煮詰める
- [x] レポート提出

**Comment by Sorarinu** [comment]
通しで見返さないまま提出すると事故る

**Comment by namazu510** [comment]
## 内容例
- システムの概要
- プロトタイプの説明
- 顧客インタビューとその解析
- 結論
- 質問内容とインタビュー結果
- 次のプロトタイプ
  - 機能一覧
  - アーキテクチャ（システム構成図、仕様要件列挙）

**Comment by arinamako** [comment]
# レポートテンプレ

プロジェクト演習　０班レポート
大学教育支援Webサービス顧客調査報告書

もくじ

１．  システムの概要　（井原）
２．  アーキテクチャ　(田胡) 
３．  プロトタイプの説明　（井垣）
４．  顧客インタビューとその解析　(羽鳥)
５．  結論　（田胡）
６．  インタビューシート

**Comment by namazu510** [comment]
## 分担
- システムの概要(新井）
- プロトタイプの説明(高畑）
- 顧客インタビューとその解析(上原）
- 結論(上原）
- 質問内容とインタビュー結果
- 次のプロトタイプ（後藤）
  - 機能一覧
  - アーキテクチャ（システム構成図、仕様要件列挙）

**Comment by namazu510** [comment]
書いて　reportフォルダにアップしました.

**Comment by namazu510** [comment]
レイアウトを治す
