### ISSUE TITLE
Git運用ルール

### ISSUE THREAD

**Issue by namazu510** [Sorarinu/ProjectP_Team#4]
- ブランチ
  - 作業単位名で切ってください
  - ブランチ切ってそのブランチの作業内容をIssueに。マージしたらIssue閉じよう
  - マージはプルリク開けてください　

以下は適当に参考でいいです　わかりやすいのあったらそれ使ってください
- コミットメッセージ

```
[動詞] 名詞 
改行
必要あれば詳細
```
- 動詞セット
  - 作成   create
  - 削除   delete
  - 更新   update
  - 追加   add
  - 修正   modify
  - 修正(バグ)   fix
  - 整理   clean

楽で簡単そうなこんなのでどうでしょう
なんか決めておかないとカオスに陥りそう

**Comment by Kouki07** [comment]
了解です

**Comment by arinamako** [comment]
おーけーです！
まだいまいち使い方わかんないんで困ったら聞きます

**Comment by Sorarinu** [comment]
作業ブランチ1つだとやりにくいから都度ブランチ切って後でマージした方がよさげ

ブランチ名は「branch_だれ」とかで

**Comment by namazu510** [comment]
たしかに作業ブランチといえどみんなで１つ使うのは大変だね
そうしよう

**Comment by Sorarinu** [comment]
ブランチ切って作業入る前にissue切って何やるか書く→マージしたときそのissue閉じるみたいな流れで

**Comment by namazu510** [comment]
結局developからトピックブランチを切ってdevelopへプルリクでマージしていくgit-flowなのかgithub-flowなのかよくわからん流れをやってしまった　
ソフト関係ないだろって仕様まとめとかあるとfeatureなのかよくわからなくなってくるなぁ　developいらなかったか・・・　
仕様関係はmasterにmaergeしてるし・・・

**Comment by namazu510** [comment]
developは死にました
よくわからなくなってきたので
masterからトピックブランチ切ってください
