### ISSUE TITLE
名詞抽出機能

### ISSUE THREAD

**Issue by Koki07** [Sorarinu/ProjectP_Team#77]

**Comment by Koki07** [comment]
英語対応していないので単語同士がくっついてしまう。(e.g. Yahoo Japan Corporation . All Rights Reserved .  -> YahooJapanCorporation . AllRightsReserved .)

▂▅▇█▓▒░(’ω’)░▒▓█▇▅▂うわあああああああ

**Comment by namazu510** [comment]
🐐 がんばえ
