### ISSUE TITLE
APIの応答

### ISSUE THREAD

**Issue by namazu510** [Sorarinu/ProjectP_Team#78]
WEBAPIの設計において
ユーザーのログイン失敗等をステータスコード200で応答し
ボディのメッセージに失敗と含めてリクエストの失敗を示す行為はバッドプラクティスである

> WebサービスでもWebAPIでもリクエストに対するレスポンスの内容を概略的に表したものがステータスコードである。 これらを正しく使うことは、WebAPIを作成する上でのマナーである。 例えば、エラーを表すコードを返さなければならないのに、成功のコードを返してしまったら、受け取った側はそれを正しいものとして認識してしまう。 つまり、ステータスコードが正しく守られていない場合は、専用のクライアントを実装しなければならず、色々なクライアントで使用出来るというWebAPIの利点を活かすことも出来ない。 そのため、誤用することなく、正しい理解をすることが求められる。　http://pokotyamu.hatenablog.com/entry/2016/05/10/190910

もっと詳しくはWEBを支える技術って本読む。

あまりよくないよねって思いながら仕様設計して、まぁいいやって思って200でステータスにNGを含めるって仕様にしちゃったんだけど・・・
本読んでたらこれ出てきてやっぱよくない気がしてきた

クライアント故の処理失敗時(ログイン失敗とか)の応答ステータスコードは4xx系で返して。ボディに失敗のJSONを含めるべきなのかな？
# 対応するかこのままいくか考えよ @Sorarinu

**Comment by Koki07** [comment]
できることなら4xx系で返した方が良いと思われる。
JSONは含めなくていいんじゃない。

**Comment by namazu510** [comment]
パラメータエラーなら400　BadRequestで返すようにしよ.
bodyはリクエストのcontent-typeヘッダに応じたものが望ましいよね
ログインくらいなら400だけでもいいけど詳細なことまで知らせたかったりするとbodyになんか書く必要があるよ
応答形式はリクエストの要求コンテンツで場合分けするのがベストプラクティスらしい　Railsでも自動生成コードはそうしてる
とりあえず現行クライアントは　Content-Type :  application/json でのリクエストだから　jsonで要求されてたらjsonの形式でエラーメッセージをbodyに含めるようにしよ

**Comment by Koki07** [comment]
なるほど。
それなら含めた方がいいね。

**Comment by Sorarinu** [comment]
基本的に http://pokotyamu.hatenablog.com/entry/2016/05/10/190910 に沿ったステータスコードを返すようにAPI修正する

BODYにはこれまで通りのJSONを含めてResponse返すよ

**Comment by namazu510** [comment]
:+1: 
了解、クライアントもそれで対応するう

**Comment by namazu510** [comment]
フロント側 #81 で対応.
