### ISSUE TITLE
プロトタイプインタビュー項目

### ISSUE THREAD

**Issue by namazu510** [Sorarinu/ProjectP_Team#95]

**Comment by namazu510** [comment]
# プロトタイプのインタビューについての準備とか
- インタビュー対象の設定
- 質問項目の設定
- 流れとかも確認する

**Comment by namazu510** [comment]
[インタビューシートてんぷら](https://service.cloud.teu.ac.jp/lecture/CSF/ktago/project/Interview.docx)

**Comment by namazu510** [comment]
# 対象ユーザー

ネットサーフィンとかよくする人

# サービスを端的に説明するワード
- すごく楽にブックマークを整理できるサービス
- ブックマークがぐちゃぐちゃな状態を解決します

**Comment by arinamako** [comment]
インタビューシート（改定）
https://drive.google.com/file/d/0B4KhWP16y5xTbm9VLURnWEU1bHM/view?usp=sharing

**Comment by namazu510** [comment]
インタビューもうすこししっかり決めよ
ポケットとかの既存サービスユーザーから人を取れるかも重要だよ

**Comment by namazu510** [comment]
土曜２４時にインタビューシートを凍結してインタビュー実施ね

**Comment by namazu510** [comment]
# 対象ユーザーとどれくらいまっちしてるか
- めっちゃ：　既存ブックマークシステムつかっててじっさいにぐちゃぐちゃでせいりしたい
- そこそこ:  なんかサービスつかってるよ、　それに少し不満があるよ

**Comment by namazu510** [comment]
対象ユーザーまとめ
集合論理関係おかしいけどまぁわかりやすさ重視でね
https://gyazo.com/5da1b5d5ea3052f3c34192e7e0f2d1ba

**Comment by namazu510** [comment]
シートまぁそこそこ書いておいたからまぁいい感じにいろいろ聞いてきてよ
結果は #96
