### ISSUE TITLE
プロトタイプインタビュー実施

### ISSUE THREAD

**Issue by namazu510** [Sorarinu/ProjectP_Team#96]

**Comment by namazu510** [comment]
土曜２４時にインタビューシートを確定するからそれに応じてインタビューやろう
水曜日の進捗会議で結果とか進捗とかお話ね

**Comment by arinamako** [comment]
インタビューの結果
[Interview-uehara1.docx](https://github.com/Sorarinu/ProjectP2016_F/files/524361/Interview-uehara1.docx)
[Interview-uehara2.docx](https://github.com/Sorarinu/ProjectP2016_F/files/524363/Interview-uehara2.docx)

**Comment by Sorarinu** [comment]
けっか
[Interview-takahata-1.docx](https://github.com/Sorarinu/ProjectP2016_F/files/524390/Interview-takahata-1.docx)
