### ISSUE TITLE
プロトタイプインタビュー分析

### ISSUE THREAD

**Issue by namazu510** [Sorarinu/ProjectP_Team#97]

**Comment by namazu510** [comment]
- サービス価値の検証
- 提供方法の妥当性の検証
- 市場調査

**Comment by namazu510** [comment]
# >分析結果に基づいて方向性の修正等行い,提示

**Comment by Koki07** [comment]
FB:リンク切れしているサイトは自動的に削除してくれると嬉しい

**Comment by namazu510** [comment]
インポートエクスポートはだるい
ポケットとかも整理はだるいと感じてる　増えてきたら扱えないとも思ってる

**Comment by namazu510** [comment]
ブックマークが多い人はあまりいない
はてブのユーザーは240万　日本の2％

ほしいといったひとはまぁいたけど
あまり整理したくない人にアピールしたら受けなかった

**Comment by namazu510** [comment]
- ブックマークが溢れて整理できない人は”なにで（コンテンツ種）”　”なんで（なにをしていて）”溢れたのか いくつかのケースをあつめる　→　そんなひとにこのサービス聞いてみる
